config/routes.rb
RedditClone::Application.routes.draw do

  resources :users
  resource :session
  resources :subs
  resources :comments
  resources :links do
    post "upvote"
    post "downvote"
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :link_id, :parent_id, :user_id, :body

  belongs_to(
  :link,
  class_name: "Link",
  foreign_key: :link_id,
  primary_key: :id
  )

  belongs_to(
  :parent,
  class_name: "Comment",
  foreign_key: :parent_id,
  primary_key: :id
  )

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  has_many(
  :children,
  class_name: "Comment",
  foreign_key: :parent_id,
  primary_key: :id
  )
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :description, :user_id

  has_many(
  :linksubs,
  class_name: "LinkSub",
  foreign_key: :link_id,
  primary_key: :id,
  inverse_of: :link
  )

  has_many :subs, through: :linksubs, source: :sub

  has_many(
  :comments,
  class_name: "Comment",
  foreign_key: :link_id,
  primary_key: :id,
  inverse_of: :link
  )

  def comments_by_parent_id
    comment_hash = {}
    comments.each do |comment|
      comment_hash[comment.id] = comment.children unless comment.children.empty?
    end
    comment_hash[nil] = comments.where("parent_id IS NULL")
    comment_hash
  end

end

app/models/link_sub.rb
class LinkSub < ActiveRecord::Base
  attr_accessible :link_id, :sub_id

  belongs_to(
  :link,
  class_name: "Link",
  foreign_key: :link_id,
  primary_key: :id
  )

  belongs_to(
  :sub,
  class_name: "Sub",
  foreign_key: :sub_id,
  primary_key: :id
  )
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  attr_accessible :user_id, :name
  validates :user_id, :name, presence: true
  validates :name, uniqueness: true


  belongs_to(
  :moderator,
  class_name: "User",
  foreign_key: :user_id,
  primary_key: :id
  )

  has_many(
  :linksubs,
  class_name: "LinkSub",
  foreign_key: :sub_id,
  primary_key: :id
  )

  has_many :links, through: :linksubs, source: :link

end

app/models/user.rb
# require 'debugger'
class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token
  attr_reader :password
  validates :password, length: {minimum: 6, allow_nil: true}
  #validates :password_digest, :email, presence: true

  has_many(
  :subs_authored,
  class_name: "Sub",
  foreign_key: :user_id,
  primary_key: :id
  )

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    if !!user && user.has_password?(password)
      return user
    end

    nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
  end

  def password=(secret)
    #p self
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def has_password?(password)
    #p self
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  attr_accessible :link_id, :user_id, :vote
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def show
    render :show
  end

  def create
    comment = Comment.new(params[:comment])
    comment.update_attribute(:user_id, current_user.id)
    if comment.save
      redirect_to comment

    else
      flash[:error] = comment.errors.full_messages
      redirect_to new_comment_url
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :user_logged_in?

  def new
    @subs = Sub.all
  end

  def upvote
    uv = UserVote.new(link_id: params[:link_id], user_id: current_user.id, vote: 1)
    uv.save!
    redirect_to link_url(params[:link_id])
  end

  def downvote
    uv = UserVote.new(link_id: params[:link_id], user_id: current_user.id, vote: -1)
    uv.save!
    redirect_to link_url(params[:link_id])
  end

  def show
    @link = Link.find(params[:id])
    @comments = @link.comments
    @comments_by_parent_id = @link.comments_by_parent_id
  end

  def create
    user = current_user
    link = Link.new(params[:link])
    link.update_attribute(:user_id, user.id)
    params[:comment][:user_id] = user.id
    link.comments.new(params[:comment])
    link.linksubs.new(sub_id: params[:sub_id])
    if link.save
      redirect_to link
    else
      flash[:error] = link.errors.full_messages
      redirect_to new_link_url
    end

    #create link + save
    #link to sub via link_subs
    #link to comment if they submit one
  end

  def user_logged_in?
    unless logged_in?
      redirect_to new_session_url
    end
  end

end

app/controllers/sessions_controller.rb
require 'debugger'

class SessionsController < ApplicationController

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if !!user
      log_in_user(user)
      redirect_to links_url
    else
      flash[:error] = "Invalid credentials"
      redirect_to new_session_url
    end
  end

  def destroy
    user = current_user
    user.reset_session_token!
    session[:session_token] = nil
    user.save!
    redirect_to new_session_url
  end


end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def create
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    user = User.new(params[:user])
    if user.save
      log_in_user(user)
      redirect_to subs_url
    else
      flash[:error] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in_user(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    user.save!
    @current_user = user
  end

  def logged_in?
    !!current_user
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/show.html.erb
Show page for comment: <%= Comment.find(params[:id]).body %><br>
<br>
<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="link_comment">Reply to this comment</label>
  <input type="text" id="link_comment" name="comment[body]">
  <input type="hidden" name="comment[parent_id]" value="<%= params[:id] %>">
  <input type="hidden" name="comment[link_id]" value="<%= Comment.find(params[:id]).link_id %>">
  <input type="submit" value="leave comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= current_user.email if !!current_user %>

<%= yield %>

</body>
</html>

app/views/links/_comments.html.erb
<ul>
  <% @comments_by_parent_id[key].each do |comment|%>
    <li><%= link_to comment.body, comment %> </li>
    <% if !!@comments_by_parent_id[comment.id] %>
      <%= render '/links/comments', key: comment.id %>
    <% end %>
  <% end %>
</ul>

app/views/links/new.html.erb
<form action="<%= links_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="link_url">Url:</label>
  <input type="text" id="link_url" name="link[url]"><br>
  <label for="link_title">Title:</label>
  <input type="text" id="link_title" name="link[title]"><br>
  <label for="link_description">Description:</label>
  <input type="text" id="link_description" name="link[description]"><br>
  <% @subs.each do |sub| %>
  <input type="checkbox" name="sub_id[]" value="<%= sub.id %>"><%= sub.name %><br>
  <% end %>
  <label for="link_comment">Comment On Your Post First:</label>
  <input type="text" id="link_comment" name="comment[body]">

  <input type="submit" value="Create Link!">
</form>

app/views/links/show.html.erb
Links Show Page for: <%= @link.url %><br>
Upvotes:<%= UserVote.find_all_by_link_id_and_vote(@link.id, 1).length %><br>
Downvotes:<%= UserVote.find_all_by_link_id_and_vote(@link.id, -1).length %><br>
<% if !UserVote.find_by_link_id_and_user_id(@link.id, current_user.id) %>
  <%= button_to("UPVOTE!!!", link_upvote_url(@link.id), method: :post)%>
  <%= button_to("DOWNVOTE!!!", link_downvote_url(@link.id), method: :post)%>
<% end %>

<%= render '/links/comments', key: nil %>

app/views/subs/new.html.erb
In the new subs view!

<form action="<%= subs_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="sub_name">Name</label>
  <input type="text" name="sub[name]" id="sub_name">
  <br>
  <input type="submit" value="Create Sub">
</form>

app/views/users/new.html.erb
<form action="<%= users_url %>" method="POST">
  <input type= "hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type=text name="user[email]">Email<br>
  <input type=password name="user[password]">Password<br>

  <input type="submit" value="log in">

</form>